In [3]:
import pandas as pd
import numpy as np

from collections import defaultdict
import math
import itertools

In [4]:
df = pd.read_excel('/polymers/GCNN_PI_glass_transition/datasets/PA_exp/PA_Tg_database_14_08_2022_not_full.xlsx', sheet_name="Tg")

# tg_data = defaultdict(lambda: defaultdict(list))

# for idx, row in df.iterrows():
#     method_idx = row['ID метода ']
#     if method_idx == 10:
#         continue
#     if math.isnan(method_idx):
#         method_idx = 9  # 9 is "unknown method"
#     tg_data[str(row['SMILES'])][int(method_idx)].append(float(row['Tg']))

# tg_data = list(list(d.values()) for d in tg_data.values())
# all_tgs = list(itertools.chain.from_iterable(list(itertools.chain.from_iterable(tg_data))))
# print(len(all_tgs))

In [5]:
df

,Unnamed: 0,# of structure,# of measurement,POLYMER ID,SMILES,Tg,UNIT,METHOD,METHOD ID,OTHER COND.,REMARK,REFERENCE,DB REFERENCE
0,0,1,-,4,INc1ccc(cc1)C1(c2ccc(cc2)NC(=O)c2ccc(cc2)Oc2cc...,567.87,[K],Askadskii,7,-,-,-,-
1,1,1,1,4,INc1ccc(cc1)C1(c2ccc(cc2)NC(=O)c2ccc(cc2)Oc2cc...,618.00,[K],Check in ref.,1,Check in ref.,Check in ref.,https://doi.org/10.1177/0954008317732121,PA-2
2,2,2,-,5,INc1ccc(cc1)C(c1ccc(cc1)NC(=O)c1ccc(cc1)Oc1cc(...,474.32,[K],Askadskii,7,-,-,-,-
3,3,2,2,5,INc1ccc(cc1)C(c1ccc(cc1)NC(=O)c1ccc(cc1)Oc1cc(...,527.00,[K],Not reported,1,Not reported,Not reported,https://doi.org/10.1016/j.memsci.2006.02.023,33604-1-1-1
4,4,3,-,6,INc1ccc(cc1)S(=O)(=O)c1ccc(cc1)NC(=O)c1cc(cc(c...,573.12,[K],Askadskii,7,-,-,-,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,222,82,-,121,INc1cccc(c1)Oc1cccc(c1)Oc1cccc(c1)NC(=O)c1cccc...,373.58,[K],Askadskii,7,-,-,-,-
223,223,82,142,121,INc1cccc(c1)Oc1cccc(c1)Oc1cccc(c1)NC(=O)c1cccc...,413.00,[K],DSC,4,Heating rate;10C/min&N2,Not reported,https://doi.org/10.1002/(SICI)1099-1581(199605...,00225-6-1-1
224,224,82,143,121,INc1cccc(c1)Oc1cccc(c1)Oc1cccc(c1)NC(=O)c1cccc...,408.00,[K],DMA,2,Not reported,Not reported,https://doi.org/10.1002/(SICI)1099-1581(199605...,00225-6-1-2
225,225,83,-,122,INc1ccc(cc1)C(C(F)(F)F)(C(F)(F)F)c1ccc(cc1)NC(...,578.64,[K],Askadskii,7,-,-,-,-
226,226,83,144,122,INc1ccc(cc1)C(C(F)(F)F)(C(F)(F)F)c1ccc(cc1)NC(...,563.00,[K],DSC,4,"Heating rate;20C/min&N2,2nd scan",Not reported,https://doi.org/10.1177/0954008302014001087,27740-4-1-1

In [6]:
df['SMILES'].value_counts().size # unique smiles

83

In [141]:
df = df.drop(columns=['Unnamed: 5', 'Unnamed: 6'])

In [142]:
df.head()

,ID,SMILES,Tg,ID ссылки,ID метода
0,1,*c1cccc(N2C(=O)c3ccc(Oc4ccc5c(c4)C(=O)N(*)C5=O...,533.0,61.0,4.0
1,1,*c1cccc(N2C(=O)c3ccc(Oc4ccc5c(c4)C(=O)N(*)C5=O...,574.0,67.0,7.0
2,1,*c1cccc(N2C(=O)c3ccc(Oc4ccc5c(c4)C(=O)N(*)C5=O...,520.0,NaN,10.0
3,2,*c1ccc(S(=O)(=O)c2ccc(N3C(=O)c4ccc(Oc5ccc6c(c5...,583.0,70.0,4.0
4,2,*c1ccc(S(=O)(=O)c2ccc(N3C(=O)c4ccc(Oc5ccc6c(c5...,582.0,NaN,10.0

In [7]:
df_Askadsky = df[df['METHOD ID'] == 7]
df_Askadsky['SMILES'].size

83

In [8]:
df_measured_tgs = df[df['METHOD ID'] != 7]

In [9]:
df_measured_tgs['SMILES'].size

144

In [14]:
df_measured_tgs_average = df_measured_tgs[['POLYMER ID', 'SMILES', 'Tg']].groupby(['POLYMER ID', 'SMILES'])['Tg'].mean().reset_index()

In [15]:
df_measured_tgs_average

    POLYMER ID                                             SMILES     Tg
0            4  INc1ccc(cc1)C1(c2ccc(cc2)NC(=O)c2ccc(cc2)Oc2cc...  618.0
1            5  INc1ccc(cc1)C(c1ccc(cc1)NC(=O)c1ccc(cc1)Oc1cc(...  527.0
2            6  INc1ccc(cc1)S(=O)(=O)c1ccc(cc1)NC(=O)c1cc(cc(c...  601.0
3            8  INc1ccc(cc1)C(C(F)(F)F)(C(F)(F)F)c1ccc(cc1)NC(...  581.0
4            9  INc1ccc(cc1)c1ccc(c(c1)C(F)(F)F)Oc1ccc2c(c1)Oc...  556.0
..         ...                                                ...    ...
78         116  INc1ccc(cc1)Oc1ccc(cc1)Oc1ccc(cc1)Oc1ccc(cc1)N...  503.0
79         117  INc1ccc(cc1)Oc1ccc(cc1)C(C(F)(F)F)(C(F)(F)F)c1...  516.0
80         118  INc1ccc(cc1)Cc1ccc(cc1)NC(=O)c1ccc(cc1)Oc1ccc(...  489.0
81         121  INc1cccc(c1)Oc1cccc(c1)Oc1cccc(c1)NC(=O)c1cccc...  410.5
82         122  INc1ccc(cc1)C(C(F)(F)F)(C(F)(F)F)c1ccc(cc1)NC(...  563.0

[83 rows x 3 columns]

In [17]:
df = df_measured_tgs_average
df.columns=["ID", "SMILES", "Tg, K"]

In [18]:
df.to_csv("/polymers/GCNN_PI_glass_transition/datasets/PA_exp/raw/target_csv.csv")

In [148]:
df_both = pd.merge(df_measured_tgs_average, df_Askadsky, on='SMILES')

In [149]:
df_both

,SMILES,Tg_x,ID,Tg_y,ID ссылки,ID метода
0,*c1c(C)c(C)c(N2C(=O)c3ccc(C(c4ccc5c(c4)C(=O)N(...,692.25,118,624.0,NaN,10.0
1,*c1c(C)cc(-c2cc(C)c(-c3cc(C)c(N4C(=O)c5ccc(C(c...,634.00,154,610.0,NaN,10.0
2,*c1c(C)cc(-c2cc(C)c(N3C(=O)c4ccc(C(c5ccc6c(c5)...,676.00,153,573.0,NaN,10.0
3,*c1c(C)cc(C)c(N2C(=O)c3ccc(-c4ccc5c(c4)C(=O)N(...,658.00,161,599.0,NaN,10.0
4,*c1c(C)cc(C)c(N2C(=O)c3ccc(C(=O)c4ccc5c(c4)C(=...,670.00,221,569.0,NaN,10.0
...,...,...,...,...,...,...
259,*c1ccccc1Cc1ccccc1N1C(=O)c2ccc(C(=O)c3ccc4c(c3...,558.00,25,452.0,NaN,10.0
260,*c1cnccc1Oc1ccc(Oc2cnccc2N2C(=O)c3ccc(C(=O)c4c...,512.00,43,416.0,NaN,10.0
261,[*]c1c(Cl)cc(Cc2cc(Cl)c(N3C(c4c(C3=O)cc(C(C(F)...,563.00,188,551.0,NaN,10.0
262,[*]c1cc(Oc2cc(n(c(=O)c(c3)c4cc5c3c(=O)n([*])c5...,560.00,87,553.0,NaN,10.0
263,[*]c1cc(Oc2ccc(S(=O)(c3ccc(Oc4cc(N5C(c6c(C5=O)...,508.00,193,505.0,NaN,10.0

In [153]:
# MAE
(df_both['Tg_x'] - df_both['Tg_y']).abs().mean()

39.52158726782724

In [154]:
# relative error
((df_both['Tg_x'] - df_both['Tg_y']).abs() / df_both['Tg_x']).mean()

0.06802241709167577

In [156]:
# Sqrt of MSE denormalized
np.sqrt(((df_both['Tg_x'] - df_both['Tg_y'])**2).mean())

57.197024404232316